apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: idblu-tts-model-cache-staging
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: idblu-tts-model-cache-staging
  resources:
    requests:
      storage: 80Gi
