apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: idblu-tts-release

resources:
  - ../base
  - namespace.yaml
  - pv-model-cache.yaml
  - pvc-model-cache.yaml

patches:
  - path: deployment-patch.yaml
  - path: configmap-patch.yaml
  - path: ingress-patch.yaml
  - path: serviceaccount-patch.yaml
  - path: secretproviderclass-patch.yaml
