apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: idblu-tts-model-cache-release
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: idblu-tts-model-cache-release
  resources:
    requests:
      storage: 80Gi
