apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: idblu-tts-secrets
spec:
  parameters:
    objects: |
      - objectName: "angel-idblu-tts-prod"
        objectType: "secretsmanager"
        jmesPath:
          - path: "IDBLU_TTS_ADMIN_KEY"
            objectAlias: "IDBLU_TTS_ADMIN_KEY"
          - path: "HF_TOKEN"
            objectAlias: "HF_TOKEN"
