apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: idblu-tts-model-cache
spec:
  accessModes:
    - ReadWriteMany
  volumeName: idblu-tts-model-cache
  resources:
    requests:
      storage: 80Gi
